### ISSUE TITLE
Charge someone per tattoo

### ISSUE THREAD

**Issue by Monkerai** [iLLeniumStudios/illenium-appearance#100]
Hello, I would really think the system could benefit from including the this ability, also being able to charge someone each time they apply a tattoo rather than only once.

**Comment by peppinoita** [comment]
You will need to add 
`config.tattoos = false`
Right before this line: 
https://github.com/iLLeniumStudios/fivem-appearance/blob/d46d6ad26e7edbf76fd09942669283b850190435/client/client.lua#L163

**Comment by Monkerai** [comment]
can it be made to charge per tattoo at the shops rather than one time payment?

**Comment by TheiLLeniumStudios** [comment]
Not for now. Maybe later it will be supported @Monkerai

**Comment by TheiLLeniumStudios** [comment]
Implemented in #205 

@Monkerai @peppinoita @zZOGZz
