### ISSUE TITLE
Menu dont show

### ISSUE THREAD

**Issue by Nodeee** [iLLeniumStudios/illenium-appearance#206]
When someone joins the server and the character is created or when they are given a /skin, the camera is changed but the creation menu does not appear

**Comment by TheiLLeniumStudios** [comment]
@Nodeee do you see any errors? Have you renamed the resource?

**Comment by Nodeee** [comment]
I only remove the ''main'' and no errors in f8 or the cmd

**Comment by TheiLLeniumStudios** [comment]
There is no -main if you download the latest release. So use the latest release. Using main is not supported and no help will be provided. Its written clearly in the readme

**Comment by TheiLLeniumStudios** [comment]
And do not rename the resource. It will not work if you rename it

**Comment by Nodeee** [comment]
I re install it, dont change the name ''illenium-appearance-4.2.0'' and when i create a new character the creation menu still does not appear. in the f8 says: Uncaught (in promise) syntaxError: Unexpected end of imput (illenium-appearance-4.2.0/web/dist/assets/index.96782610.js:70

**Comment by TheiLLeniumStudios** [comment]
´The name needs to be `illenium-appearance`

**Comment by TheiLLeniumStudios** [comment]
You downloaded the "Source Code" instead of the actual illenium-appearance.zip file from the release

**Comment by Nodeee** [comment]
Thank you, i change the name illenium-appearance-4.2.0 to illenium-appearance and it works! I really appreciate the help you gave me.
