### ISSUE TITLE
Character dont save/load in qb-multicharacter

### ISSUE THREAD

**Issue by Nodeee** [iLLeniumStudios/illenium-appearance#207]
Hello again, now I have a problem, every time I create a character and disconnect, when I reconnect it does not show the character selection. im sorry for wasting your time with this errors but i re instal qbmultichar and change the codes and it doesnt load either :c

**Comment by TheiLLeniumStudios** [comment]
Please create a post in the support channel over my discord. This is a place for actual issues and not support.
https://discord.illenium.dev

**Comment by Nodeee** [comment]
Im in the discord but not veryfied yet

**Comment by TheiLLeniumStudios** [comment]
Closing as not an issue
