### ISSUE TITLE
Character creation issue

### ISSUE THREAD

**Issue by MriKNG** [iLLeniumStudios/illenium-appearance#209]
**The Issue:**
Whenever someone creates a new character and choose their apartment, they are greeted with an infinite black screen. It then pops up the UI of the apartment and they have to disconnect, load back in and then they have a default skin without the ability to change their clothes. 

**Error that pops up in console:**
[script:qb-apartments] SCRIPT ERROR: Execution of native 000000002f7a49e6 in script host failed: Argument at index 1 was null.
[script:qb-apartments] > <unknown> (@oxmysql/dist/build.js:22252)
[script:qb-apartments] > processTicksAndRejections (node:internal/process/task_queues:96)

**Scripts:**
QB-Apartments is up to date, QB-Multicharacter and QB-Spawn (Marcostom32) is up to date and Illenium-appearance is up to date from the releases. I also updated my OXMYSQL. These worked perfectly fine on initial installation and after a couple days started giving me this error. All the installation instructions were followed.

**Comment by TheiLLeniumStudios** [comment]
It doesn't seem like an issue related to illenium-appearance. It is coming from qb-apartments. I would suggest opening up an issue on their repository @MriKNG

**Comment by MriKNG** [comment]
I will, i'll keep y'all updated. Appreciate it.
