### ISSUE TITLE
job outfits

### ISSUE THREAD

**Issue by Chip-W** [iLLeniumStudios/illenium-appearance#235]
I setup a bunch of job outfits in the config menu, but none show up at the job location.  it's just blank.  I'm sure I'm missing something, just not sure what it is.

Otherwise, everything works perfectly.

QBCore

**Comment by TheiLLeniumStudios** [comment]
You most likely have BossManagedOutfits = true. Change it to false in config if you want to use predefined outfits in the config @Chip-W and use discord for help / support please
