### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GhostV-Survival** [iLLeniumStudios/illenium-appearance#236]
hey can qnyone help me with the appearance please?

i have to trigger these
TriggerEvent('ghost:hudHide', true) - HIDE HUD
TriggerEvent('ghost:hudHide', false) - SHOW HUD

idk where to implement it 😦

**Comment by TheiLLeniumStudios** [comment]
@GhostV-Survival search for startPlayerCustomization in client/client.lua

you can add the hide trigger before calling that function and then add the show trigger inside of the callback for startPlayerCustomization

**Comment by GhostV-Survival** [comment]
![image](https://user-images.githubusercontent.com/100316482/214619860-033ab7c2-5715-4171-8b78-5de166a48fa1.png)
not working =(
![image](https://user-images.githubusercontent.com/100316482/214620288-003b936c-264d-4b61-bde1-dbac41be0034.png)

**Comment by Gameadictive** [comment]
on Jan 25, 2023
