### ISSUE TITLE
Menu is not showing

### ISSUE THREAD

**Issue by xrb936** [iLLeniumStudios/illenium-appearance#237]
[    330657] [b2802_GTAProce]        CrBrowserMain/ Synchronous loading (@illenium-appearance/web/dist/assets/index.96782610.js:599)
[    331657] [b2802_GTAProce]        CrBrowserMain/ TypeError: Cannot read properties of undefined (reading 'masks') (@illenium-appearance/web/dist/assets/index.96782610.js:32)
[    331657] [b2802_GTAProce]        CrBrowserMain/ TypeError: Cannot read properties of undefined (reading 'hats') (@illenium-appearance/web/dist/assets/index.96782610.js:32)
[    331657] [b2802_GTAProce]        CrBrowserMain/ Uncaught TypeError: Cannot read properties of undefined (reading 'masks') (@illenium-appearance/web/dist/assets/index.96782610.js:32)

**Comment by TheiLLeniumStudios** [comment]
Not an issue with illenium-appearance. Check your configs. You’ve messed it up or using old config in a newer version

**Comment by xrb936** [comment]
I downloaded the latest release and didn't change anything in config beside the blips name and the price.
