### ISSUE TITLE
Error with latest version

### ISSUE THREAD

**Issue by soniXx123** [iLLeniumStudios/illenium-appearance#255]
Some players cant change there clothes. all the time there getting this error

![image](https://user-images.githubusercontent.com/35350615/218510097-a6c3ef32-35f3-44ea-965c-129b99a79b5f.png)

**Comment by TheiLLeniumStudios** [comment]
@soniXx123 The players have unnamed outfits which breaks the sorting, hence the error

**Comment by TheiLLeniumStudios** [comment]
For now you can remove the table.sort function that is on line 477 and it should fix the issue for you. I'm waiting on ox_lib to add support for required fields to have it properly handled. But until then, the temporary fix should work fine

**Comment by soniXx123** [comment]
![image](https://user-images.githubusercontent.com/35350615/218552195-ac753fcc-d6d7-4043-8d10-558f2d3d380c.png)
:D

**Comment by TheiLLeniumStudios** [comment]
@soniXx123 unfortunately I can't do anything about that. You will need to update the outfits in the database and assign a random name to them
