### ISSUE TITLE
UI with delayed when opening for the first time

### ISSUE THREAD

**Issue by FlexBuf** [iLLeniumStudios/illenium-appearance#256]
Hello, just as a doubt, it happens that sometimes when you open the clothing menu for the first time, it takes a long time to open, then the second time it opens, it works without problems, is the delay in opening the interface normal? happens to the whole server

**Comment by TheiLLeniumStudios** [comment]
Hi. Yes it is because the first request loads up a lot of data for the tattoos and translations etc, so it is expected. I will look into improving it in the future but until then, it will be like this

**Comment by FlexBuf** [comment]
fix?

**Comment by TheiLLeniumStudios** [comment]
@FlexBuf it is not a bug. It will be like this until I have time to improve it but it is not a priority at all right now. You can try to do it yourself and create a PR if you can’t wait. I will close this issue now
