### ISSUE TITLE
Possible update

### ISSUE THREAD

**Issue by Dejvi1** [iLLeniumStudios/illenium-appearance#258]
Hi i was wondering if you could add option to turning cameras- to completely turn around not just left and right but also behind..
While creating outfits there is often issue with arms bugging thru outfit but players cannot actually turn around to see if is it fine..
Thanks <3

**Comment by TheiLLeniumStudios** [comment]
Hi @Dejvi1 . You can already do that using the 3rd button. The player rotates 180 degree instead of the camera but it does what you need

**Comment by Dejvi1** [comment]
oh amazing thank you so much ! :3
