### ISSUE TITLE
first spawn dead

### ISSUE THREAD

**Issue by Hushibane** [iLLeniumStudios/illenium-appearance#264]
when first time join server, my hp goes low and after click save menu my char dead
![image](https://user-images.githubusercontent.com/125734637/223085842-3c0c1c2a-bfd7-4807-8515-1abebb8b0c87.png)

**Comment by Gellipapa** [comment]
@Hushibane Hi! You should download latest version. You can download here: https://github.com/iLLeniumStudios/illenium-appearance/releases/download/v5.0.1/illenium-appearance.zip 

It's works perfectly!
