### ISSUE TITLE
Player skin won't load in esx_multicharacter

### ISSUE THREAD

**Issue by tony-stark-17** [iLLeniumStudios/illenium-appearance#266]
In the main branch the latest push of ox_lib cache.ped is being used which is a loop every 100ms which is good but the issue is that when spawnmanager spawn the ped and instantly the skinchanger is used to set the skin the player skin won't load as the cache.ped doesn't exist

**Comment by TheiLLeniumStudios** [comment]
@tony-stark-17 spawnmanager has nothing to do with skins. It just spawns a ped

**Comment by tony-stark-17** [comment]
Well yeah in esx_multicharacter once the spawnmanager spawns the ped instantly the skinchanger event is called which causes this issue as the ox_lib playerped hasn't yet updated

**Comment by ADRNALN** [comment]
I am also having issues with skins loading especially on a new character it only spawns the player with a head and this is on QBCore, I reverted the recent update and no longer have issues

**Comment by VinnyTheLegend** [comment]
Same here for my QBcore server. Not loading the ped/skin in the character select menu. Tested with qb-multicharacter and bb-multicharacter

**Comment by TheiLLeniumStudios** [comment]
For now stay on the latest release. main can be broken and no support is provided if you are using that. It will take a few weeks for me to take a look at try to debug the issue on main

**Comment by AnxietyPills** [comment]
same for me

**Comment by tony-stark-17** [comment]
Any update??

**Comment by TheiLLeniumStudios** [comment]
@tony-stark-17 This is fixed in #292 

Please try out the main branch and feel free to re-open if the problem persists
