### ISSUE TITLE
Loadout bug

### ISSUE THREAD

**Issue by Alfita2021** [iLLeniumStudios/illenium-appearance#269]
When you get a weapon, exit the server and reconnect, the weapon does not appear but it is in the sql.

**Comment by TheiLLeniumStudios** [comment]
It is not related to illenium-appearance. The resource does not touch the player's loadout at all

**Comment by Alfita2021** [comment]
Thank you for your quick response
this is what I have in the config
![image](https://user-images.githubusercontent.com/88886043/224827243-0fd13c5c-3fc4-459f-97ac-427da27bff46.png)
Here is a video:
https://imgur.com/a/JUKv8bC

**Comment by TheiLLeniumStudios** [comment]
@Alfita2021 you are not using the latest release but rather the main branch. No support is provided if you use main as it can and most likely is always broken since new features and improvements haven't been tested and have made into a release. Switching to the latest release zip i.e., 5.0.1 will fix your issue

**Comment by Alfita2021** [comment]
@TheiLLeniumStudios he probado la ultima release y sigue sucediendo lo mismo

**Comment by Alfita2021** [comment]
@TheiLLeniumStudios I have found a possible solution. If I start esx_skin and skinchanger and then illenium-appearance. I have the weapon.

**Comment by TheiLLeniumStudios** [comment]
That is the problem actually. You cannot use esx_skin and skinchanger with illenium-appearance. It is mentioned in the docs. If you use them then no support is provided

**Comment by Alfita2021** [comment]
I know, but if I don't start esx_skin and skinchanger, when I exit the server with weapons and reconnect, I don't have the weapons.

**Comment by Alfita2021** [comment]
@TheiLLeniumStudios It was definitely an illenium-appearance problem, I have updated the script, it was missing a TriggerEvent. Now it works perfectly without esx_skin or skinchanger.

**Comment by Alfita2021** [comment]
I will contribute but I would have liked you to help me since it was clear that it was a script problem. (Not to discredit your work, I just wanted to let you know since it didn't feel very good that you didn't help me). (Sorry for my english)

**Comment by TheiLLeniumStudios** [comment]
@Alfita2021 Apologies. I have been extremely busy and due to the lack of knowledge of how ESX works in detail I assumed that the problem was coming from some other end. My bad. Thank you for contributing the fix ❤️

**Comment by Alfita2021** [comment]
@TheiLLeniumStudios I hear you. Thank you for your work. ❤️❤️
