### ISSUE TITLE
Appearance creation bug

### ISSUE THREAD

**Issue by Kroa0912** [iLLeniumStudios/illenium-appearance#272]
When the player clicks the rotate button, the player's character seems to only move like this; he doesn't rotate 180 or 360.

sorry the clip is too laggy.
https://vimeo.com/810423275

**Comment by TheiLLeniumStudios** [comment]
Not an issue with the code. And use discord for support without tagging me and you will get help @Kroa0912 . Github is only for actual issues that are known and need to be fixed in code. Your issue is your location, as you are near the fence so the player cannot rotate
