### ISSUE TITLE
result test for me

### ISSUE THREAD

**Issue by Bobbbe** [iLLeniumStudios/illenium-appearance#273]
Hello, I would like to tell you about some problems I encountered with the illenium_appearance.
- When we arrive, the character starts running, 1 time out of 4 and we have to do our configuration with the ped running and in the corner of the wall.
-Another aspect, the ped disappears 1 time out of 4 after having saved the modifications with the plastic surgeon of the hospital, impossible to make it appear with a disconnection, I have to restart the server. Despite these small drawbacks, I like your resource but unfortunately I can't keep it because it is unstable for the moment, if you make some updates, I will be happy to test it again and give you my results. .
I'm on dedicate/ovh, linux/debian, I use the pterodactyl panel to control the server. I am under esx_legacy last version,
I use the OX resources. Thank you and good day :)

**Comment by Bobbbe** [comment]
he starts running towards the corner of the wall by pressing the button to turn around, to have the rear view.

**Comment by Bobbbe** [comment]
Another thing, we can't remove our mask, glasses, hat, helmet without going to the store! and since we are removing the esx_skin and skinchanger, the mask and accessory shop no longer works, they must be removed too, but it is these resources that allow us to remove our mask and others... can be added some functions and a menu to remove items without having to go to the clothing store :)

**Comment by TheiLLeniumStudios** [comment]
@Bobbbe I am unable to reproduce any issues that you have mentioned. Please download and use the latest release https://github.com/iLLeniumStudios/illenium-appearance/releases/tag/v5.0.1

Make sure to use `illenium-appearance.zip` and not main / source code

The mask / accessory shop cannot work with illenium-appearance since it would require making changes to esx_accessories

**Comment by TheiLLeniumStudios** [comment]
Closing as not reproduceable and lack of response
