### ISSUE TITLE
Armor issues?

### ISSUE THREAD

**Issue by geekgfx** [iLLeniumStudios/illenium-appearance#278]
im using qb-core and i am experiencing the armor regenerating it will reset, i am searching for the problem myself but just wondering if you knew it was here, cause it wasnt doing it before i put illenium in so i just wanna make sure.

**Comment by TheiLLeniumStudios** [comment]
Explain the problem in detail. What you have mentioned is vague. Post a video and explain the behavior

**Comment by TheiLLeniumStudios** [comment]
Closing as not reproduceable and lack of response
