### ISSUE TITLE
Problem with TriggerEvent('skinchanger:getSkin', function(skin)

### ISSUE THREAD

**Issue by Edvesse** [iLLeniumStudios/illenium-appearance#281]
Hello,

In my ambulance job script, for the locker rooms, I have a male, female locker room depending on the skin_sex, but when I come on the marker, it flashes. If I remove the line TriggerEvent('skinchanger:getSkin', function(skin), the blip blinks more. before with esx_skin and skinchanger it worked fine, would you have a solution? Here is the code.

TriggerEvent('skinchanger:getSkin', function(skin)
                if skin.sex == 0 then
                    if SudVestiaireHomme <= Config.Marker.DrawDistance then
                        sleep = 0
                        DrawMarker(Config.Marker.Type, Config.Sud.vestiairehomme.x, Config.Sud.vestiairehomme.y, Config.Sud.vestiairehomme.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.2, 0.15, 93, 182, 229, 255, false, false, 0, true, false, false, false)
                    end
                else
                    if SudVestiaireFemme <= Config.Marker.DrawDistance then
                        sleep = 0
                        DrawMarker(Config.Marker.Type, Config.Sud.vestiairefemme.x, Config.Sud.vestiairefemme.y, Config.Sud.vestiairefemme.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.2, 0.15, 93, 182, 229, 255, false, false, 0, true, false, false, false)
                    end
                end
            end

**Comment by TheiLLeniumStudios** [comment]
Github is for actual issues and not for support / help. Use discord for support or help

**Comment by Edvesse** [comment]
Yeah but no one reply to my post !
