### ISSUE TITLE
invisible after update

### ISSUE THREAD

**Issue by SmithyDevelopment** [iLLeniumStudios/illenium-appearance#286]
after updating the script, when you load in the character is invisible and not loading prev saved ped data

**Comment by TheiLLeniumStudios** [comment]
@SmithyDevelopment use the latest release zip and not main / source code. It is clearly mentioned in the docs. No support is provided if you use the main branch. That's why there are proper releases for everything

**Comment by SmithyDevelopment** [comment]
i knew that.... ooops lol 
Many thanks
