### ISSUE TITLE
tattoo not save

### ISSUE THREAD

**Issue by yasassri5613** [iLLeniumStudios/illenium-appearance#288]
apply tattoos but fly out and fly again all tattoos remove.how can i fix

**Comment by TheiLLeniumStudios** [comment]
@yasassri5613 I cannot reproduce this issue. Please share your framework, its version, what version of illenium-appearance are you using (in fxmanifest.lua), and steps to reproduce the issue, And also share a video of the behavior and then I can take a look

**Comment by TheiLLeniumStudios** [comment]
Closing as not reproduceable and lack of response

**Comment by boby123456** [comment]
> @yasassri5613 I cannot reproduce this issue. Please share your framework, its version, what version of illenium-appearance are you using (in fxmanifest.lua), and steps to reproduce the issue, And also share a video of the behavior and then I can take a look

I am facing with simular issue, i am using ESX Legacy 1.10.5, so basically if i do try to apply tatoo nothing even happens, players charatcer does not gets any tattoos
