### ISSUE TITLE
Bug Access Blacklisting

### ISSUE THREAD

**Issue by nurrifqialhusaini** [iLLeniumStudios/illenium-appearance#290]
Hello, i wanna report "bug abuse" for blacklist access.
All player can access blacklist clothes / hair with arrow keyboard. 
Maybe u must be make validation when player use arrow keyboard not just when click the button arrow

This how to access "blacklist" clothes / hair
1. Open store
2. Just make sure where the "blacklist" clothes, example : shirts
3. go to shirts panel and dont use the "arrow button" at ui, just use your arrow keyboard.
4. and buy it, dont forget save.

**Comment by nurrifqialhusaini** [comment]
can u make some validation when player at drawables 0 and click arrow down keyboard ?
because this critical bug

**Comment by TheiLLeniumStudios** [comment]
Duplicate of #164
