### ISSUE TITLE
Infinite black screen??? idfk

### ISSUE THREAD

**Issue by DeputyDutch** [iLLeniumStudios/illenium-appearance#299]
So any time that I attempt to change over to this version of appearance from fivem-appearance. It causes the screen immediately after selecting and loading a character to be an infinite loop of a black screen?? I get no errors from the console or in game F8 console either. I followed the docs to the letter for the integration into qb-multicharacter and updated all necessary dependencies. Still it seems to break at some point. This is of course after dropping and redoing the tables as the instructions stated so unless there is a step someplace that I missed, which I am doubtful of, I'm stuck between a rock a hard place.

Appreciate any thoughts on what would cause an infinite black screen after selecting and loading a character.

**Comment by TheiLLeniumStudios** [comment]
@DeputyDutch If you follow the docs properly, it doesn't happen. This is what you specifically missed:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/104288623/234402144-bd6de2fc-66c4-4f8b-9b52-8a5acc49956c.png">
