### ISSUE TITLE
fxmanifest missing files

### ISSUE THREAD

**Issue by nzkfc** [iLLeniumStudios/illenium-appearance#301]
Not 100% sure, but just updated to latest and on boot says files are missing that are listed in fxmanifest.lua, I assume it's just a cleanup thing that was missed but might throw people off:

https://i.imgur.com/NEdwFLp.png

<3

**Comment by TheiLLeniumStudios** [comment]
@nzkfc not sure what you downloaded but there are no missing files that are mentioned in fxmanifest.lua as of the latest release v5.1.0. Same goes with the main branch but you're not supposed to use that

**Comment by nzkfc** [comment]
Ahh yeah this was before our chat, so can close.
