### ISSUE TITLE
cant get it to work

### ISSUE THREAD

**Issue by TinkerGaming87** [iLLeniumStudios/illenium-appearance#303]
![image](https://user-images.githubusercontent.com/117561252/235298275-98924138-ecb1-4b69-a533-873903e449f9.png)
[](url)

i followed install have latest version and latest version of ox_lib and put the sql files in database any idea what would give me this error and menu not work

**Comment by TheiLLeniumStudios** [comment]
Read the docs again and you will figure it out. The error is also telling you what you did wrong
