### ISSUE TITLE
Saving outfits and give them a name right after "buying"?

### ISSUE THREAD

**Issue by jvstin2k** [iLLeniumStudios/illenium-appearance#312]
Hey, this not an issue, more like a question.

Is there any way to give the outfit you just bought a name instead of saving it and then going out of the menu and then give it a name?

Thanks for answers!

**Comment by TheiLLeniumStudios** [comment]
There isn’t a way at the moment. Feel free to implement it and create a PR. Or create a suggestion on my discord
