### ISSUE TITLE
performance problems, the menu takes a long time to open and suffers from lag

### ISSUE THREAD

**Issue by FlexBuf** [iLLeniumStudios/illenium-appearance#313]
performance problems, the menu takes a long time to open and suffers from lag.

Will they improve performance and optimization?

**Comment by TheiLLeniumStudios** [comment]
1. It only takes a few seconds to cache the menu the 1st time it loads for a player in game. That cannot be improved. It is how much time gta takes to load all the data for appearance
2. There is no lag
3. I have no plans to work on further optimisations
4. 4. Feel free to contribute improvements
