### ISSUE TITLE
Issue with UI and AddItems function

### ISSUE THREAD

**Issue by xhackax47** [iLLeniumStudios/illenium-appearance#314]
Hello everyone and sorry for my english, i am on ESX and i have some issues with the UI (bug and blocked) and the AddItems() function can someone help me please? Thanks by advance for your advices ^^

**Code UI :**

![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/35836274/df075f44-8403-431f-b457-84cfb18d8c1e)

**Log ERROR UI**

`[     68859] [b2802_GTAProce]        CrBrowserMain/ Uncaught (in promise) SyntaxError: Unexpected end of input (@illenium-appearance/web/dist/assets/index.96782610.js:70)
`
`[    106140] [b2802_GTAProce]        CrBrowserMain/ SyntaxError: Unexpected end of input (:0)`

**Code AddItems :**

![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/35836274/285bde33-de63-42a9-ba11-88511b885cf9)

**Log ERROR AddItems**

`[     99078] [b2802_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @illenium-appearance/client/client.lua:69: attempt to call a nil value (field 'AddItems')^7
`

**Comment by TheiLLeniumStudios** [comment]
1. No answer support is provided for the UI if you make changes to JS files
2. ESX does not support boss managed outfits which is clearly mentioned in the installation docs but you still enabled it. Disabling it will fix the issues
3. Next time create a post over my discord for support. This is only for actual issues and yours is not

**Comment by xhackax47** [comment]
Ok but I didn't do anything in js files it's the original ... Anyway thx for your answer and sorry to bother you ....

**Comment by xhackax47** [comment]
Ok but I didn't do anything in js files it's the original ... Anyway thx for your answer and sorry to bother you ....

**Comment by TheiLLeniumStudios** [comment]
Redownload the latest release then. And don’t change the config file or any file to see if the error goes away. If it does, then it’s due to some config that you modified @xhackax47
