### ISSUE TITLE
On playerdropped unable to load Theme/Appearance configuration when reconnecting

### ISSUE THREAD

**Issue by EpKouhia** [iLLeniumStudios/illenium-appearance#316]
When player will crash or timeout from the server reconnecting will cause timeouts loading theme configuration and locales. Difficult to debug further without current NUI source.

![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/15001445/89a16a78-0441-4f7e-b78e-2b41c5853d24)

**Comment by TheiLLeniumStudios** [comment]
@EpKouhia its not something I have control over. Players have to quit the game and then open it again to have it working properly
