### ISSUE TITLE
SCRIPT ERROR: @illenium-appearance/client/zones.lua:61: attempt to index a nil value (field 'job')

### ISSUE THREAD

**Issue by Edvesse** [iLLeniumStudios/illenium-appearance#321]
Hello, 

I have this message when i have do the update from 5.0.1 in 5.3.0.

![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/89741780/6930798b-45f1-4367-a9d9-3130afa222d8)

Can you help me please?

I can no longer access any clothing shops

Thanks you for your job !

**Comment by TheiLLeniumStudios** [comment]
@Edvesse use discord for support. This is a place for actual issues
https://discord.illenium.dev
