### ISSUE TITLE
request failed due to timeout

### ISSUE THREAD

**Issue by veeayye** [iLLeniumStudios/illenium-appearance#322]
hi, not sure if someone is able to help, but i am just someone who plays on fivem servers and ive noticed that anytime a city i fly into uses this creation/clothing menu etc it never pops up for me and i am stuck as a ped. ive cleared my fivem cache and i switched which version of fivem i am using. when i was using beta the menu would never pop up for me, i switched to release and i was finally able to see the menu and create a character, once i flew out and went back in my character was back a ped and the menu no longer popped up for me. Again, not sure if anyone has a solution as im not a developer, city only etc. im just someone who plays fivem and realized that whenever a city uses this script unfortunatly im not able to create a char. 
![image (5)](https://github.com/iLLeniumStudios/illenium-appearance/assets/135642134/71b8cebd-7d15-407b-bd4b-ff487caad970)

**Comment by TheiLLeniumStudios** [comment]
Hi @veeayye 
You will have to contact the developers of the server you play on to fix the issue as it is not a resource issues
