### ISSUE TITLE
have a missing clothing option

### ISSUE THREAD

**Issue by illanthony** [iLLeniumStudios/illenium-appearance#328]
cant find out why scarfAndChains isnt pulling up as a clothing option i only have 9 out of the 10 clothing options but 5 out of the 5 props
![Screenshot (13)](https://github.com/iLLeniumStudios/illenium-appearance/assets/136317737/e40255fb-bbec-44cd-aadf-ad995cfac593)

**Comment by TheiLLeniumStudios** [comment]
Disable tracker config. You have a tracker on
