### ISSUE TITLE
[Issue] Multiple Departments Unable to Use "Police"

### ISSUE THREAD

**Issue by rxnm** [iLLeniumStudios/illenium-appearance#335]
Hey, loving the script guys, job well done. However I have a slight problem, in the configs where it says (police) for police officers to get the clothing menu, it doesn't work for my multiple departments I have set up as "leo", I have (Police, Bcso, Sahp) all which connect to LEO. I have tried many things, and the way it usually works is like "police", "bcso", "sahp", "leo", but none is working, I have tried multiple ways. I have looked through the scripts to find anything related to PlayerJob.name in which I would usually change to PlayerJob.type and then leo as such. How can I fix it to work please?

Thx :)

**Comment by TheiLLeniumStudios** [comment]
I do not support that sort of config as it's dependent on framework changes done independently. You'll unfortunately have to debug this on your own or create a support post over my discord and someone else who might have dealth with this can help you
