### ISSUE TITLE
Error witth Ox_lib

### ISSUE THREAD

**Issue by b2gomes** [iLLeniumStudios/illenium-appearance#338]
[    c-scripting-core] Creating script environments for illenium-appearance
[       script:ox_lib] Unable to determine current resource version for 'illenium-appearance' 
[           resources] Started resource illenium-appearance

Illenium version: 5.40
ox_lib version: 3.6.3
![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/97984058/7f2870a9-e13c-4306-bd8b-3f90b3c392c8)

**Comment by TheiLLeniumStudios** [comment]
Read the docs and follow them properly and you won't run into this

**Comment by b2gomes** [comment]
i followed all the docs, the only change that i made is the 
setr illenium-appearance:locale "pt-BR"
because i'm brazilian

**Comment by TheiLLeniumStudios** [comment]
@b2gomes have you read this?
![Screenshot_20230720_191052_Chrome](https://github.com/iLLeniumStudios/illenium-appearance/assets/104288623/bdac6d60-ff56-4b11-ba5c-bb133e7d8c0a)
This is what you haven't done which is why you see the error

**Comment by b2gomes** [comment]
Downloaded again and worked, ty
