### ISSUE TITLE
screen freeze

### ISSUE THREAD

**Issue by dtachi** [iLLeniumStudios/illenium-appearance#339]
the E to buy in the clothing store doesnt come up but when i click E, it freezes my screen, and also when i add the ped it does the same thing

**Comment by TheiLLeniumStudios** [comment]
Read the docs and follow them and you don't run into the issue

**Comment by dtachi** [comment]
i have had the screen for a while now and it has been running fine until now

**Comment by TheiLLeniumStudios** [comment]
I don't know how to fix your issue based on the information you have provided. And there have been 0 reports of what you have mentioned. Read the docs again and reinstall. If it stilld doesn't work then use discord for support. The issue tracker is for actual bugs / enhancements

**Comment by dtachi** [comment]
okay i fixed it for now

**Comment by dtachi** [comment]
i think its the lastest OX_lib
