### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by eden8gamer** [iLLeniumStudios/illenium-appearance#348]
idk why he do that 
![](https://cdn.discordapp.com/attachments/876170200637145089/1143234797435633844/image.png)

![](https://cdn.discordapp.com/attachments/876170200637145089/1143234797024596112/image.png)

**Comment by TheiLLeniumStudios** [comment]
This is not the place to ask for help on user related issues. Use discord, follow the proper support format and someone can take a look if all the information is provided
