### ISSUE TITLE
Facing this Error

### ISSUE THREAD

**Issue by nightmare7vx** [iLLeniumStudios/illenium-appearance#349]
![Screenshot (180)](https://github.com/iLLeniumStudios/illenium-appearance/assets/143146637/36e02253-3c1e-4701-84f1-54d947591831)

facing this issue after installing illenium appearance
i cant even give myself clothing menu using admin menu

**Comment by nightmare7vx** [comment]
![Uploading Screenshot (181).png…]()

**Comment by nightmare7vx** [comment]
![Uploading Screenshot (181).png…]()

**Comment by nightmare7vx** [comment]
![Uploading Screenshot (182).png…]()

**Comment by nightmare7vx** [comment]
![Uploading Screenshot (183).png…]()

**Comment by TheiLLeniumStudios** [comment]
Issues for actual issues related to code, not for support. Use discord for support
