### ISSUE TITLE
Timeout Error After Following Installation Instructions

### ISSUE THREAD

**Issue by patriotgaming** [iLLeniumStudios/illenium-appearance#350]
After installing im receiving this error
![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/22457902/56c9b5f9-f4e1-4eb9-b75c-50388c0553d6)
I have the locales set in svr cfg, started under ox_lib, basically everything stated in the installation is done including the provides esx_skin and skinchanger

**Comment by patriotgaming** [comment]
its everytime someone loads in, relogging multiple times does not fix

**Comment by TheiLLeniumStudios** [comment]
Issues for actual issues related to code, not for support. Use discord for support
