### ISSUE TITLE
Can't delete character

### ISSUE THREAD

**Issue by eternalcityrp** [iLLeniumStudios/illenium-appearance#354]
[ script:oxmysql] Error: qb-core was unable to execute a transaction!
[ script:oxmysql] DELETE FROM phone_messages WHERE citizenid = 'UVB69950'
[ script:oxmysql] Unknown column 'citizenid' in 'where clause'

It will say the character is deleted but when it goes back to character selection, that character is still there.

**Comment by TheiLLeniumStudios** [comment]
Not related to illenium-appearance

**Comment by eternalcityrp** [comment]
thank you for the quick response!
