### ISSUE TITLE
saving clothing issue.

### ISSUE THREAD

**Issue by STCMFILMZ** [iLLeniumStudios/illenium-appearance#360]
read the docs and it still isnt working i did everything step by step as it say in the docs... can somebody help me ... all the guy is telling me to do is read the docs... can somebody else thats been having this issue show me what you did?

**Comment by TheiLLeniumStudios** [comment]
You didn't. Read the docs again and follow them properly and you won't run into issues

**Comment by Jieseldablanco** [comment]
> You didn't. Read the docs again and follow them properly and you won't run into issues

Is this your only response? Seems a lot of people are having the same issue and they clearly say they are reading the docs and following directions.
