### ISSUE TITLE
Cant Save current Outfit.

### ISSUE THREAD

**Issue by kaho0409** [iLLeniumStudios/illenium-appearance#365]
I saved it with a name using Save current Outfit, but it does not appear in Change Outfit.

I installed it according to the instructions.
What you previously saved with qb-clothing is in ChangeOutfit.
Probably not saved. What should I do?

**Comment by TheiLLeniumStudios** [comment]
Read the docs again. You have not followed them correctly

**Comment by Keekay-OD** [comment]
Did you ever fix this issue? I followed the docs as well

**Comment by IAmDanielPeter** [comment]
Same here.

**Comment by Keekay-OD** [comment]
Im just coming back to this, i I think what fixed it was updating the DB.  Msg me if anyone has issues, ill be happy to help!

**Comment by NAF-ORO** [comment]
I need help

**Comment by NAF-ORO** [comment]
> Im just coming back to this, i I think what fixed it was updating the DB.  Msg me if anyone has issues, ill be happy to help! 

I need help

**Comment by hugomra** [comment]
i need help with this please

**Comment by Jock-J** [comment]
was there ever a resolution to this?

**Comment by Keekay-OD** [comment]
> was there ever a resolution to this?

Pretty sure it was a db issue.  Message me on discord keeekay_yktv

**Comment by Jock-J** [comment]
> > was there ever a resolution to this?
> 
> Pretty sure it was a db issue. Message me on discord keeekay_yktv

cant seem to message you on discord heres an invite link to me if you would please:- https://discord.gg/kaEFm4cB

**Comment by Jock-J** [comment]
> > > was there ever a resolution to this?
> > 
> > 
> > Pretty sure it was a db issue. Message me on discord keeekay_yktv
> 
> cant seem to message you on discord heres an invite link to me if you would please:- https://discord.gg/kaEFm4cB

cant find you on discord thought you were sorting the phone for me sir?
