### ISSUE TITLE
players loading in as peds

### ISSUE THREAD

**Issue by Holliday4** [iLLeniumStudios/illenium-appearance#366]
[script:illenium-appe] SCRIPT ERROR: @illenium-appearance/server/server.lua:20: table index is nil

it seems like player outfit code wont load it what im assuming but why.? some people load into server fine and others dont even get to the multichar because they basically time out. it seems to be lower end pcs taking to long to load resources. already tried changing multichar and everything/ illenium seems to be good but above error pops up when a pl;ayer cant load and ends up a ped
trying to get a crash log from saomeone its happening to because its not happening to me

**Comment by TheiLLeniumStudios** [comment]
Use discord for support. This is for actual issues and not support
