### ISSUE TITLE
PLASTIC SURGEON: PED NOT LOADING/SHOWING BUG???

### ISSUE THREAD

**Issue by ChlxeThomson** [iLLeniumStudios/illenium-appearance#368]
SURGEON PED NOW ISN;T LOADING REGARDLESS WHAT I AM TRYING TO FIX IT. I HAVE TRIED MULTIPLE LOCATIONS TO MAKE SURE ITS NOT MLO ISSUE ETC AND STILL WONT LOAD. ONLY TEXT LOADS???
<img width="1910" alt="Screenshot 2023-10-17 205328" src="https://github.com/iLLeniumStudios/illenium-appearance/assets/58238399/6d303e7e-25f2-4832-89c8-8148cd60ced8">

**Comment by ChlxeThomson** [comment]
Here is my code for it

{
        type = "surgeon",
        coords = vector4(-1859.99, -350.21, 53.74, 145.24),
        size = vector3(5, 5, 5),
        rotation = 45,
        usePoly = false,
        showBlip = true,
        points = {
            vector3(298.84417724609, -572.92205810547, 43.26),
            vector3(296.39556884766, -575.65942382812, 43.26),
            vector3(293.56317138672, -572.60675048828, 43.26),
            vector3(296.28656005859, -570.330078125, 43.26)
        }
    },

**Comment by TheiLLeniumStudios** [comment]
THIS IS NOT SUPPORT. AND YOU CANNOT ENABLE PEDS WITH ZONES

**Comment by ChlxeThomson** [comment]
I fixed it by the way, it’s cause i had the target set to false haha
