### ISSUE TITLE
Clothing won't save. Getting SQL error

### ISSUE THREAD

**Issue by Strat78** [iLLeniumStudios/illenium-appearance#369]
script:illenium-appe] SCRIPT ERROR: @illenium-appearance/server/server.lua:200: illenium-appearance was unable to execute a query!
[script:illenium-appe] Unknown column 'components' in 'field list'
[script:illenium-appe] INSERT INTO player_outfits (citizenid, outfitname, model, components, props) VALUES (?, ?, ?, ?, ?) ["YZR50939","test","mp_m_freemode_01","[{\"texture\":0,\"drawable\":0,\"component_id\":0},{\"texture\":0,\"drawable\":0,\"component_id\":1},{\"texture\":0,\"drawable\":0,\"component_id\":2},{\"texture\":0,\"drawable\":0,\"component_id\":3},{\"texture\":0,\"drawable\":0,\"component_id\":4},{\"texture\":0,\"drawable\":0,\"component_id\":5},{\"texture\":0,\"drawable\":0,\"component_id\":6},{\"texture\":0,\"drawable\":0,\"component_id\":7},{\"texture\":0,\"drawable\":0,\"component_id\":8},{\"texture\":0,\"drawable\":0,\"component_id\":9},{\"texture\":0,\"drawable\":0,\"component_id\":10},{\"texture\":0,\"drawable\":0,\"component_id\":11}]","[{\"prop_id\":0,\"drawable\":2,\"texture\":0},{\"prop_id\":1,\"drawable\":-1,\"texture\":-1},{\"prop_id\":2,\"drawable\":0,\"texture\":0},{\"prop_id\":6,\"drawable\":1,\"texture\":0},{\"prop_id\":7,\"drawable\":-1,\"texture\":-1}]"]
[script:illenium-appe] > handler (@illenium-appearance/server/server.lua:200)
[script:illenium-appe] > <unknown> (@oxmysql/dist/build.js:22274)
[script:illenium-appe] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by TheiLLeniumStudios** [comment]
Read the docs again. Not an issue with illenium-appearance
