### ISSUE TITLE
Players clothing overlap

### ISSUE THREAD

**Issue by WillIShocker** [iLLeniumStudios/illenium-appearance#370]
When a player takes off their clothing, there is clothing underneath. We have checked everything we can think of, but the issue persists. Have tested it with qb-clothing and the issue does not persist.

**Comment by WillIShocker** [comment]
I have attempted to adjust constants as well.

**Comment by TheiLLeniumStudios** [comment]
That is not an issue with the script. You have to adjust the constant properly. See the faq channel on my discord
