### ISSUE TITLE
Menu not showing, error when opening menu

### ISSUE THREAD

**Issue by Nikolaaa24** [iLLeniumStudios/illenium-appearance#371]
detailed error: `error during NUI callback appearance_get_locales: @illenium-appearance/game/nui.lua:4: attempt to index a nil value (field '?')`

**Comment by Nikolaaa24** [comment]
No I have not done anything in files nor in config.

**Comment by TheiLLeniumStudios** [comment]
Read the docs again. You have not set the right locales
