### ISSUE TITLE
-1 on all menu items

### ISSUE THREAD

**Issue by AntonMars** [iLLeniumStudios/illenium-appearance#372]
![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/140720796/60ac78af-c7e3-428b-9f29-74cc77992d0c)
After clean install, I can't get drawables and textures to show anything more than -1?
Followed all instructions, added tables in DB, restarted, no other players, no migration.

**Comment by AntonMars** [comment]
Followed all instructions, added tables in DB, restarted...

**Comment by TheiLLeniumStudios** [comment]
Change your ped to freemode
