### ISSUE TITLE
Clothing Not Saving, Cannot Generate New Outfit Code

### ISSUE THREAD

**Issue by spanxurazz** [iLLeniumStudios/illenium-appearance#376]
Ever since the new qbcore update I am unable to save outfits and cannot generate outfit codes. Is there something I missed. I installed the latest version, everything is imported properly. but we still cannot save outfits and stuff. There are no errors that are currently apparent.

**Comment by TwanMC** [comment]
Same here

**Comment by TheiLLeniumStudios** [comment]
Closing as this is a support issue and not something wrong with the resource
