### ISSUE TITLE
Few issues with arms, belts and pricing

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [iLLeniumStudios/illenium-appearance#377]
I've adjusted the pricing for clothing to be 50, but you keep have to pay 100 to change clothes.

I'm unable to change **arms** and **belts**, the arms thing makes this happen:

![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/97805195/d3e4f623-4d8c-4859-b3af-e78c88237aaf)

**Comment by TheiLLeniumStudios** [comment]
Closing as this is a support issue and not something wrong with the resource
