### ISSUE TITLE
Joboutfits help needed

### ISSUE THREAD

**Issue by ImBeefy** [iLLeniumStudios/illenium-appearance#384]
So i have been all over this now.

I cant make the clothing rooms for ems and police work.
The menu comes up, but no outfits available in the work menu.
the command for bossmenu is saying im missing a sql with job_grades but im on QB.

Been through installation guide many times, i cant find any information on this.
Does the preset clothing options not work or am i missing a config?

**Comment by TheiLLeniumStudios** [comment]
Disable boss managed outfits if you want to define in config

**Comment by ImBeefy** [comment]
> Disable boss managed outfits if you want to define in config

Thank you so much.
I tried that before, but it didnt work and now it does.
Obviously i made a mistake, but thank you so much for the quick reply! Love the script! <3
