### ISSUE TITLE
Unsure of Issue... Script Issues

### ISSUE THREAD

**Issue by LoadedGuns** [iLLeniumStudios/illenium-appearance#395]
[script:illenium-appe] SCRIPT ERROR: @illenium-appearance/server/permissions.lua:4: attempt to get length of a nil value (field 'Aces')
[script:illenium-appe] > callbackResponse (@ox_lib/imports/callback/server.lua:60)
[script:illenium-appe] > handler (@ox_lib/imports/callback/server.lua:76)

I keep getting the above errors over and over again, unsure whats triggering it, Ive changed nothing in my server in the last several days and this started yesterday. Searched, and I cant find anything to solve this any ideas?

**Comment by LoadedGuns** [comment]
I did a fresh install of both Illenium and Ox-Lib today just to see if that was the issue, and nothing has changed

**Comment by TheiLLeniumStudios** [comment]
Use the latest release and not main.
