### ISSUE TITLE
Mining script change clothes back to normal after exiting job

### ISSUE THREAD

**Issue by djthemask** [iLLeniumStudios/illenium-appearance#396]
Hi there,

I am running a mini script that basically changes your clothes while you are on "duty". I am trying to add a function where when you exit the job it returns you your appearence before starting the job but for some reason it doesnt work. 

I tried to force a reload skin as that returns the peds clothes as they where before but it doesnt work. Any tips on what im doing wrong?
![imagen](https://github.com/iLLeniumStudios/illenium-appearance/assets/34578760/3c577bde-c860-4b7d-a554-2343a58f9305)

Appearently that doesnt work im not sure if i need to add an export.

**Comment by djthemask** [comment]
So how could i add it? I also tried to add it as a client event but that also doesnt work. I would highly apreciate your helping hand :(

**Comment by djthemask** [comment]
![imagen](https://github.com/iLLeniumStudios/illenium-appearance/assets/34578760/ec2cdf43-0f65-4b77-ac80-1933b4d2048f)

**Comment by djthemask** [comment]
@TheiLLeniumStudios whenever u have a second please <3

**Comment by TheiLLeniumStudios** [comment]
```lua
TriggerEvent("illenium-appearance:client:reloadSkin", true)
```

**Comment by djthemask** [comment]
Fantastic that worked perfectly! There is also a function that resets the clothes when exiting the working area. When i apply the same command it says i can't do it in a vehicle, how could i force the reloadskin execution even while in vehicle, or how would you suggest i could apply a function that would work whilist in a vehicle?

Thanks a million for your time @TheiLLeniumStudios i really apreciate it!
