### ISSUE TITLE
Issues with SQL

### ISSUE THREAD

**Issue by SpazMachine** [iLLeniumStudios/illenium-appearance#397]
[script:illenium-appe] SCRIPT ERROR: @illenium-appearance/server/server.lua:198: illenium-appearance was unable to execute a query!
[script:illenium-appe] Query: INSERT INTO player_outfits (citizenid, outfitname, model, components, props) VALUES (?, ?, ?, ?, ?)
[script:illenium-appe] ["YDP91604","Test PD","mp_m_freemode_01","null","[{\"drawable\":0,\"component_id\":0,\"texture\":0},{\"drawable\":0,\"component_id\":1,\"texture\":0},{\"drawable\":150,\"component_id\":2,\"texture\":0},{\"drawable\":0,\"component_id\":3,\"texture\":0},{\"drawable\":126,\"component_id\":4,\"texture\":1},{\"drawable\":93,\"component_id\":5,\"texture\":0},{\"drawable\":25,\"component_id\":6,\"texture\":9},{\"drawable\":0,\"component_id\":7,\"texture\":0},{\"drawable\":15,\"component_id\":8,\"texture\":0},{\"drawable\":49,\"component_id\":9,\"texture\":0},{\"drawable\":0,\"component_id\":10,\"texture\":0},{\"drawable\":213,\"component_id\":11,\"texture\":0}]"]
[script:illenium-appe] Unknown column 'props' in 'field list'

**Comment by SpazMachine** [comment]
So I re did the SQL using the provided SQL script and now I get this. 

[script:illenium-appe] SCRIPT ERROR: @illenium-appearance/server/server.lua:198: illenium-appearance was unable to execute a query!
[script:illenium-appe] Query: INSERT INTO player_outfits (citizenid, outfitname, model, components, props) VALUES (?, ?, ?, ?, ?)
[script:illenium-appe] ["YDP91604","test","mp_m_freemode_01","null","[{\"drawable\":0,\"component_id\":0,\"texture\":0},{\"drawable\":0,\"component_id\":1,\"texture\":0},{\"drawable\":150,\"component_id\":2,\"texture\":0},{\"drawable\":0,\"component_id\":3,\"texture\":0},{\"drawable\":126,\"component_id\":4,\"texture\":1},{\"drawable\":93,\"component_id\":5,\"texture\":0},{\"drawable\":25,\"component_id\":6,\"texture\":9},{\"drawable\":0,\"component_id\":7,\"texture\":0},{\"drawable\":15,\"component_id\":8,\"texture\":0},{\"drawable\":49,\"component_id\":9,\"texture\":0},{\"drawable\":0,\"component_id\":10,\"texture\":0},{\"drawable\":213,\"component_id\":11,\"texture\":0}]"]
[script:illenium-appe] Unknown column 'props' in 'field list'

**Comment by TheiLLeniumStudios** [comment]
No you didn't add the SQL correctly. Read the docs again. There's nothing wrong with the script or SQL that's provided
