### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by AKGamingYT0** [iLLeniumStudios/illenium-appearance#399]
![image](https://github.com/iLLeniumStudios/illenium-appearance/assets/36809982/d9bd2adc-8f42-4113-8c61-3c1409745233)

**Comment by killy60** [comment]
I have the same problem since today although everything was working correctly before it was impossible to enter my server
![Sans titre](https://github.com/iLLeniumStudios/illenium-appearance/assets/24763666/41162799-27bc-4e40-9750-a76eff34bd55)

**Comment by TheiLLeniumStudios** [comment]
Try reinstalling or reverting back to default configs. Not able to reproduce this
