### ISSUE TITLE
blipConfig error

### ISSUE THREAD

**Issue by RoODRiGoOB** [iLLeniumStudios/illenium-appearance#403]
Hi, thx for the wonderful script.  
I keep getting an error each time i start the server.

client/blips.lua:15: attempt to index a nil value (local 'blipConfig') 

<img width="1059" alt="Captura de Tela 2024-03-12 às 11 21 37 AM" src="https://github.com/iLLeniumStudios/illenium-appearance/assets/163150424/5aecea80-8818-4c9a-a02c-37f0fbd83fc4">

Any clue?

**Comment by TheiLLeniumStudios** [comment]
You've messed up your config. Revert to the original one
