### ISSUE TITLE
tattoo shop

### ISSUE THREAD

**Issue by GilesKysel** [iLLeniumStudios/illenium-appearance#423]
when i undress in the tattoo store i always wear different clothes. body and legs can't be tattooed. how can i solve this problem?

![Screenshot 2024-06-08 020654](https://github.com/iLLeniumStudios/illenium-appearance/assets/119689944/27ee1f57-b1e1-4efd-8745-2f1d926a5aac)

![Screenshot 2024-06-08 020725](https://github.com/iLLeniumStudios/illenium-appearance/assets/119689944/c761a46c-8424-4577-a42d-9c055e23ec33)

**Comment by TheiLLeniumStudios** [comment]
Not an issue. See faq on discord
