### ISSUE TITLE
SCRIPT ERROR: @illenium-appearance/server/database/playerskins.lua:12: illenium-appearance was unable to execute a query!

### ISSUE THREAD

**Issue by sabotage93thctv** [iLLeniumStudios/illenium-appearance#435]
![image_2024-07-06_072429847](https://github.com/iLLeniumStudios/illenium-appearance/assets/152351449/f3d48c0a-4f90-463b-b399-c89ba4674024)
    

hi i had a problem after a database was removed due to error since then we have had bug after bug to fix now we have this issue and people are loading in as random peds after making there charecter

**Comment by sabotage93thctv** [comment]
also tryed to join the discord first but the captcha has a error

**Comment by sabotage93thctv** [comment]
the error only comes up after trying to change cloths

**Comment by sabotage93thctv** [comment]
same as when u try to  use admin menu in any way to save ped

**Comment by TheiLLeniumStudios** [comment]
Read the docs again. You have not followed them correctly. Reapply SQL as mentioned in the docs
