### ISSUE TITLE
Problem with "ClothingRooms" for jobs.

### ISSUE THREAD

**Issue by SerafinXIV** [iLLeniumStudios/illenium-appearance#437]
Hello,
I would like to ask for help here because the jobs locker rooms do not currently work via illenium.
We have configured the points and outfits in config.lua but when we go to the position, unfortunately nothing happens.
Any advice or help would be welcome please.

PS: We are running ESX 1.10.5, we have the latest release of illenium appearance and no apparent errors in the panel or F8.
Besides, I posted here because Discrord bot seems "broken" currently.

**Comment by TheiLLeniumStudios** [comment]
ClothingRooms work as intended as long as you configure them properly by following the 1 example that's in config. I cannot help you more as the errors should clearly surface on your server / client consoles that you can fix (assuming that you have put in the config correctly)
