### ISSUE TITLE
Female ped floating

### ISSUE THREAD

**Issue by deputystrand** [iLLeniumStudios/illenium-appearance#438]
After updated new version it seems the female ped is floating in air
https://cdn.discordapp.com/attachments/970276320678391848/1259924219412742185/image.png?ex=669167de&is=6690165e&hm=dfc67ea2bab46f3c037f9279ea1cb92a496d9e6c00005f80fe60ab97ddc14da7&

**Comment by hussyainy** [comment]
better use other image hosting as discord link now only valid for 24 hours

**Comment by TheiLLeniumStudios** [comment]
Floating is common when the female shoes are not added correctly as a custom item. Nothing related to the resource

**Comment by deputystrand** [comment]
my clothing not item sir
