### ISSUE TITLE
Problem with Player tattoo when use setPedAppearance export

### ISSUE THREAD

**Issue by hussyainy** [iLLeniumStudios/illenium-appearance#443]
when i run this export  it seems that the online player Tattoo setting will change to like a default tattoo settings. and it will overwrite the user tattoo settings set in the tattoo shop.

exports['illenium-appearance']:setPedAppearance(peduser, skindata)

**Comment by TheiLLeniumStudios** [comment]
That is expected, as tattoos are part of the appearance. So you need to get the tattoos using getPedTattoos and then set them in the skindata before calling setPedAppearance
