### ISSUE TITLE
Peds still don´t spawn in

### ISSUE THREAD

**Issue by LettyR** [iLLeniumStudios/illenium-appearance#445]
.... Soooo Thanks Sir for Nothing.
Let me response to the "solved" and closed Ticket:

I read the Config: 

Config.EnablePedsForShops = true
Config.EnablePedsForClothingRooms = true
Config.EnablePedsForPlayerOutfitRooms = true

Config.EnablePedMenu = true
Config.PedMenuGroup = "group.admin"

So What´s the Matter here ? 
The Ped.lua is also in Place.
Still no Peds in the Shops.
Think they doesn´t care about your " Read your Config" Tip ....

**Comment by TheiLLeniumStudios** [comment]
Again, with you providing such detailed config, I can only tell you to enable target in config. Anything else is not supported with peds. Closing
