### ISSUE TITLE
WARNING!!

### ISSUE THREAD

**Issue by Jesolok** [iLLeniumStudios/illenium-appearance#448]
im having an issue when selecting characters im getting a black loading screen and it wont move past im not sure what is causing this issue but i am getting this warning can anyone help with this thanks in advance

[script:illenium-appe] Warning: [natives] TRIGGER_CLIENT_EVENT_INTERNAL: client 1 is not the same as the target 65536. This happens when the oldId from the playerJoining event is used. Use source instead.

**Comment by ENT510** [comment]
noticed this with latest artifacts

**Comment by ENT510** [comment]
this is a simple issue from ox lib, already fixed download latest version
