### ISSUE TITLE
Suggestion: Add ped head variations.

### ISSUE THREAD

**Issue by RackoonAlan** [iLLeniumStudios/illenium-appearance#90]
So a lot of the peds in GTA5 have variations to their head. The pictures i'm adding are the same ped but with the different head variation. To expand on this as well, the head variations also have textures which usually are beards and things like that as also shown in the picture.. It would be really nice to see a feature added that gives you the option to change the head variation and texture of the heads. 

https://imgur.com/a/MtPcABO

**Comment by ZZG994521** [comment]
HI sir , how do you do it

**Comment by geekgarage** [comment]
i would like to bump this and link to your discord where there is a forum thread on this
https://discord.com/channels/969974469974163466/1046253675821154404

**Comment by TheiLLeniumStudios** [comment]
@RackoonAlan @ZZG994521 @geekgarage support added in #201 
![image](https://user-images.githubusercontent.com/104288623/210281484-0bf76bc8-ad2d-4b5e-91dd-0ca87364c056.png)
